### ISSUE TITLE
HTML Validator

### ISSUE THREAD

**Issue by MisahSaid** [lemuelmgsn/eigen-website#1]
hi, ik heb een testje gedaan met html validator en daaruit krijg ik eigenlijk 1 issue die telkens terug kwam (easy fix ;)). Het ging over de svg's.

"Warning: <svg> attribute "height" has invalid value "32px", wat dit inhoud is eigenlijk dat het niet correct is.
![Screenshot 2024-08-23 at 23 18 26](https://github.com/user-attachments/assets/c0d3405b-2c3b-4004-bdbe-f4c1ca29f6e9)

maar wat niet correct eraan is dat je 'px' erachter hebt, "SVG-standaardwaarden voor height en width moeten numerieke waarden zijn zonder een eenheid zoals px (pixels). De SVG-specificatie verwacht eenvoudigweg getallen zoals 32 in plaats van 32px." 

Oplossing, px weglaten! 

 [de html validator die ik heb gebruikt:](https://chromewebstore.google.com/detail/html-validator/mpbelhhnfhfjnaehkcnnaknldmnocglk)

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/eigen-website/blob/22651f24af8b54546023e49e146064c606ac46e7/views/partials/left-arrow-svg.ejs#L1

https://github.com/lemuelmgsn/eigen-website/blob/22651f24af8b54546023e49e146064c606ac46e7/views/partials/right-arrow-svg.ejs#L3

Gefixt! bedankt!
